# Generated by Django 3.2.2 on 2021-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(default='', max_length=250)),
                ('semester', models.CharField(choices=[('Pee', 'Pee'), ('Poop', 'Poop'), ('Walk', 'Walk'), ('Eat', 'Eat'), ('Medicine', 'Medicine'), ('Nothing', 'Nothing')], default='', max_length=20)),
            ],
        ),
    ]
