# Generated by Django 3.2.2 on 2021-06-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='semester',
            new_name='activity',
        ),
    ]
