# Generated by Django 3.2.2 on 2021-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_rename_semester_event_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reporter',
            field=models.CharField(choices=[('Mark R.', 'Mark R.'), ('Katerina R.', 'Katerina R.'), ('Dawn R.', 'Dawn R.'), ('Maria R.', 'Maria R.')], default='', max_length=20),
        ),
    ]
