# Generated by Django 3.2.2 on 2021-06-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20210615_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(choices=[('Peed', 'Peed'), ('Poop', 'Poop'), ('Walk', 'Walk'), ('Eat', 'Eat'), ('Medicine', 'Medicine'), ('Nothing', 'Nothing')], default='', max_length=20),
        ),
    ]
